version: "3.8"

services:
  react-docker:
    container_name: react-docker
    build:
      context: ./
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/app/react-docker
      - /usr/src/app/react-docker/node_modules
